name: "terraform"

on:
  workflow_dispatch:
    inputs:
      subscription:
        description: "Enter Subscription Name"
        required: true
      service:
        description: "Enter Service Name"
        required: true
      environment:
        description: "Select the Environment"
        required: false
        type: choice
        options: 
          - 
          - dev
          - nprd
          - prod

env:
  SERVICE: ${{ github.event.inputs.service }}
  ENVIRONMENT: ${{ github.event.inputs.environment }}

jobs:
  Terraform_Init:  
    name: Terraform Plan "${{ env.SERVICE }}" "${{ env.ENVIRONMENT }}"
    runs-on: [self-hosted]    

    steps:
      - name: Checkout
        uses: actions/checkout@v3